```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
forestfires <- read.csv("~/forestfires/forestfires.csv")
glimpse(forestfires)
```

```{r}
library(cluster)
## Convert day to number
forestfires$day <- recode(forestfires$day, "sun"= 7, "mon"= 1, "tue"= 2, "wed"= 3, "thu"= 4, "fri"= 5, "sat"= 6)

## Convert month to number
forestfires$month <- recode(forestfires$month, "jan"=1, "feb"=2, "mar"=3, "apr"=4, "may"=5, "jun"=6, "jul"=7, "aug"=8,"sep"=9,"oct"=10,"nov"=11, "dec"=12)

forestfires <- forestfires %>% na.omit()
```

```{r}
sil_width <-vector()

for(i in 2:10){
  pms <- pam(forestfires, i)
  sil <- silhouette(pms$cluster, dist(forestfires))
  sil_width[i]<-mean(sil[,3])
}

ggplot() + 
  geom_line(aes(x=1:10,y=sil_width)) +
  scale_x_continuous(name="k",breaks=1:10) +
  scale_y_continuous(name="Silhouette Width (PAM)")

for(i in 2:10){
  kms <- kmeans(forestfires, i)
  sil <- silhouette(kms$cluster, dist(forestfires))
  sil_width[i]<-mean(sil[,3])
}

ggplot() + 
  geom_line(aes(x=1:10,y=sil_width)) +
  scale_x_continuous(name="k",breaks=1:10) +
  scale_y_continuous(name="Silhouette Width (K-Means)")
  

ff_pam <- pam(forestfires, 2)
ff_kms <- kmeans(forestfires, 2)


forestfires <- forestfires %>% mutate(cluster=ff_pam$clustering) %>% mutate(cluster_factor=as.factor(ff_pam$clustering))


forestfires_2 <- forestfires %>% filter(cluster==2)

forestfires_3 <- forestfires %>% filter(area != 0)
glimpse(forestfires_3)
forestfires %>% filter(cluster==1) %>% arrange(-area)

forestfires %>% filter(month==1)
forestfires %>% filter(area > 600)

new_ff <- forestfires %>% filter(area < 600) 


new_ff %>% ggplot(aes(month, area, color=cluster_factor)) + geom_point() + scale_x_continuous(name="Month", breaks=1:12) + scale_y_continuous(name="Burned Area of Forest (ha)") + theme_classic() + scale_color_manual(name="Cluster", values=c("red", "blue"), labels=c("1", "2")) + ggtitle("Burned Area of Forest vs Month")
```

```{r}
library(GGally)
forestfires %>% mutate(cluster_factor=as.factor(ff_pam$clustering)) %>% ggpairs(col=1:13, aes(color=cluster_factor), upper = list(continuous = wrap("cor", size = 2)), axisLabels = "none", proportions = 20)

#theme(axis.text = element_text(size = 5))
#forestfires %>% mutate(cluster_factor=as.factor(ff_pam$clustering)) %>% ggpairs(col=5:13, aes(color=cluster_factor))
```



```{python}
from sklearn.linear_model import LinearRegression 
from sklearn.linear_model import HuberRegressor 
```

```{python}
hub = HuberRegressor()

X = np.array(forestfires_2.temp)[:, np.newaxis]
Y = np.array(forestfires_2.area)


hub.fit(X, Y)

print("[temp, area] Huber Regression Intercept: ", hub.intercept_)

print("[temp, area] Huber Regression Coefficient: ", hub.coef_)
```



```{r}
ggplot(forestfires,aes(wind, temp)) +
  geom_point() +
  geom_smooth(method='lm')

temp.lm <- lm(temp ~ wind, data=forestfires)
summary(temp.lm)



cormat <- forestfires%>%select_if(is.numeric)%>%na.omit %>% cor(use="pair")
cormat

#cormat_1 <-cormat %>% as.data.frame %>% rownames_to_column("var1")

tidycor <- cormat %>%
  as.data.frame %>%
  rownames_to_column("var1") %>%
  pivot_longer(-1, names_to = "var2", values_to = "correlation")

tidycor

tidycor %>% ggplot(aes(var1, var2, fill=correlation)) + 
  geom_tile() + 
  scale_fill_gradient2(low="red", mid="white", high = "blue") +
  geom_text(aes(label=round(correlation,2)),color = "black", size = 2)+ #overlays correlation values
  theme(axis.text.x = element_text(angle = 90)) + #flips the x-axis labels
  coord_fixed()
```

```{r}
forestfires %>% ggplot(aes(temp, area)) + geom_point()
forestfires_2 %>% ggplot(aes(DMC, area)) + geom_point()
```

